<?php
return array(
	'mode_aggressive'			=> 'Agressif',
	'mode_angry'				=> 'En colère',
	'mode_assist'				=> 'Assistance',
	'mode_canattack'			=> 'Peut attaquer',
	'mode_canmove'				=> 'Peut se déplacer',
	'mode_castsensorchase'		=> 'Capteur de sort en poursuite',
	'mode_castsensoridle'		=> 'Capteur de sort au repos',
	'mode_changechase'			=> 'Change de poursuite',
	'mode_changetargetchase'	=> 'Change de cible en poursuite',
	'mode_changetargetmelee'	=> 'Change de cible en mêlée',
	'mode_detector'				=> 'Détecteur',
	'mode_fixeditemdrop'		=> 'Drop d’objet fixe',
	'mode_ignoremagic'			=> 'Ignore la magie',
	'mode_ignoremelee'			=> 'Ignore la mêlée',
	'mode_ignoremisc'			=> 'Ignore les autres dégâts',
	'mode_ignoreranged'			=> 'Ignore les attaques à distance',
	'mode_knockbackimmune'		=> 'Immunisé au recul',
	'mode_looter'				=> 'Ramasseur',
	'mode_mvp'					=> 'MVP',
	'mode_norandomwalk'			=> 'Immobile',
	'mode_randomtarget'			=> 'Cible aléatoire',
	'mode_skillimmune'			=> 'Immunisé aux compétences',
	'mode_statusimmune'			=> 'Immunisé aux statuts',
	'mode_targetweak'			=> 'Cible faible',
	'mode_teleportblock'		=> 'Bloque la téléportation',
)
?>
