<?php
return array(
	'A' => 'Admin',
	'B' => 'Magasin d’achat',
	'C' => 'Consommé',
	'D' => 'Volé',
	'E' => 'Envoyé par courrier',
	'F' => 'Récupération liée',
	'G' => 'Stockage de guilde',
	//'H' => '',
	'I' => 'Mis aux enchères',
	//'J' => '',
	'K' => 'Bank',
	'L' => 'Ramassé',
	'M' => 'Monstre',
	'N' => 'NPC (Script)',
	'O' => 'Produit',
	'P' => 'Joueur',
	'Q' => 'Quête',
	'R' => 'Stockage',
	'S' => 'PNJ (boutique)',
	'T' => 'Échangé',
	'U' => 'MVP',
	'V' => 'Vendu en vending',
	//'W' => '',
	'X' => 'Autre',
	'Y' => 'Loterie',
	'Z' => 'Fusionné',
	'$' => 'Cash',
);
?>
